config/routes.rb
Drcalleja::Application.routes.draw do
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'experience' => 'pages#experience'
  
  root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end


  def action
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
	<div class="footer">
		<small>
			<%= link_to "onemonehtrails", "http://onemonehtrails.com" %>
			
			<a href="http://onemonehtrails.com">One moenth rails</a>

		</small>	
	</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <a class="brand" href="#">Dr Sergio Calleja</a>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
        <ul class="nav">
        	<li> <%= link_to "Home", root_path %> </li>
			<li> <%= link_to "About", about_path %> </li>
			<li> <%= link_to "Contact", contact_path %> </li>
			<li> <%= link_to "Experience", experience_path %> </li>
		</ul>

 		<ul class="nav pull-right">
        	<li> <%= link_to "login", '#' %> </li>
        </ul>

      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Drcalleja</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
			<%= render 'layouts/header' %>

			<div class="container">
				
	<%= yield %>

			<%= render 'layouts/footer' %>

	</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<p>
	<%= link_to "onemonthrails", "http://onemoenthrails.com" %>

	

app/views/pages/contact.html.erb
<h1> Contact us<h1>

app/views/pages/experience.html.erb
<h1> Experience <h1>

app/views/pages/home.html.erb
<div class="hero-unit">
<h1>Dr Calleja</h1>

<p>
	Find me in app/views/pages/home.html.erb
	<%= link_to "onemonthrails", "http://onemonthrails.com" %>

	<a href="http://onemonthrails.com">One moneth rails</a> 
	application.

</p>
<p>
	<%= link_to "sign up now!", "#", class: "btn btn-priamry btn-large"%> 

	<a href="#">sign up Now!</a>
</p>

</div>

<ul class="thumbnails">
			  <li class="span4">
			    <div class="thumbnail">
			      <img data-src="holder.js/300x200" alt="">
			      <h3>Entrepreneurship</h3>
			      <p>Thumbnail caption...</p>
			    </div>
			  </li>

			  <li class="span4">
			    <div class="thumbnail">
			      <img data-src="holder.js/300x200" alt="">
			      <h3>Health Activities</h3>
			      <p>Thumbnail caption...</p>
			    </div>
			  </li>
			  
			  <li class="span4">
			    <div class="thumbnail">
			      <img data-src="holder.js/300x200" alt="">
			      <h3>Other Projects</h3>
			      <p>Thumbnail caption...</p>
			    </div>
			  </li>
</ul>